FROM       dlip/centos
MAINTAINER Dane Lipscombe <dane@lipscombe.com.au> v11.0.12-2014.05.14

RUN rpm -Uvh https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-server-11.0.12-1.el6.x86_64.rpm
